title: konh4cks
description: This blog contains write-ups of the things that I researched, learned, and wanted to share to others.
author: konh4cks
github: https://github.com/konh4cks
about: Digital security enthusiast driven by curiosity and sharing discoveries.
google_analytics: 
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/konh4cks"

share:
  twitter_username: 

urls:
    - text: whoami
      url: /whoami
    - text: Projects
      url: /projects
    - text: Resources
      url: /resources
      
url: "https://konh4cks.github.io/"
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-seo-tag
  - jemoji
  - jekyll-auto-image
  - jekyll-feed
  - jekyll-sitemap 

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
